{% set name = "nomad-camels" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels-{{ version }}.tar.gz
  sha256: ef4320977b88d2d3684e8725bcc92014926beebaa3a8dc88176b685e01b25bef

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=61.0
    - pip
    - libgl-devel  # [linux]
  run:
    - pyqtgraph >=0.13.3
    - suitcase-nomad-camels-hdf5 >=0.4.4
    - uvicorn >=0.19.0,<0.22.0
    - python
    - pyside6 >=6.6.0
    - bluesky >=1.9.0
    - ophyd >=1.6.4
    - databroker >=1.2.5
    - pandas >=1.4.2
    - numpy >=1.23.0
    - h5py >=3.7.0
    - xarray >=2022.3.0
    - qtpy >=2.1.0
    - pip >=21.1.2
    - wheel >=0.36.2
    - setuptools >=54.2.0
    - matplotlib-base >=3.6.2
    - scipy >=1.10.1
    - ipython >=8.4.0
    - lmfit >=1.0.2
    - pyepics >=3.5.1
    - future >=0.18.2
    - pillow >=9.1.1
    - toolz >=0.11.2
    - pymongo >=4.1.1
    - partd >=1.2.0
    - dask-core >=2023.4.0
    - fsspec >=2022.5.0
    - packaging >=21.3
    - cloudpickle >=2.1.0
    - pyyaml >=6.0
    - jinja2 >=3.1.2
    - parso >=0.8.3
    - jedi >=0.18.1
    - colorama >=0.4.4
    - pims >=0.6.1
    - slicerator >=1.1.0
    - tifffile >=2022.5.4
    - imageio >=2.19.3
    - uncertainties >=3.1.7
    - pint >=0.20.1
    - pytz >=2022.1
    - requests >=2.26.0
    - numcodecs >=0.9.1
    - zarr >=2.11.3
    - fasteners >=0.17.3
    - asciitree >=0.3.3
    - zict >=2.2.0
    - heapdict >=1.0.1
    - attrs >=21.4.0
    - six >=1.16.0
    - pyparsing >=3.0.9
    - asteval >=0.9.27
    - networkx >=2.8.3
    - locket >=1.0.0
    - intake >=0.6.4
    - msgpack-python >=1.0.4
    - appdirs >=1.4.4
    - entrypoints >=0.4
    - markupsafe >=2.1.1
    - python-dateutil >=2.8.2
    - jsonschema >=4.6.0
    - cycler >=0.11.0
    - tqdm >=4.64.0
    - traitlets >=5.3.0
    - boltons >=21.0.0
    - certifi >=2022.5.18.1
    - humanize >=4.1.0
    - prettytable >=3.3.0
    - pygments >=2.12.0
    - decorator >=5.1.1
    - backcall >=0.2.0
    - pickleshare >=0.7.5
    - wcwidth >=0.2.5
    - tzlocal >=4.2
    - idna >=3.3
    - urllib3 >=1.26.9
    - asttokens >=2.0.5
    - executing >=0.8.3
    - fonttools >=4.33.3
    - doct >=1.0.5
    - cachetools >=5.3.0
    - mongoquery >=1.4.2
    - pyrsistent >=0.18.1
    - kiwisolver >=1.4.2
    - iso8601 >=1.0.2
    - pytables >=3.7.0
    - numexpr >=2.8.4
    - qt-material >=2.12
    - pyserial >=3.5
    - pyvisa >=1.13.0
    - pyvisa-py >=0.7.0

test:
  imports:
    - nomad_camels
  commands:
    # - pip check
  requires:
    - pip

about:
  home: https://fau-lap.github.io/NOMAD-CAMELS/
  summary: CAMELS is a configurable measurement software, targeted towards the requirements of experimental solid-state physics.
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
